name: make-sqlite-db

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as SQLite-DB
    tags:
      - v*      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Elŝutu la dosierojn 
      uses: actions/checkout@v1
    - name: Saluto al docker.pkg.github.com
        # https://github.community/t5/GitHub-Actions/Use-docker-images-from-GitHub-Package-Registry/td-p/30407    
        # https://github.com/actions/starter-workflows/blob/master/ci/docker-push.yml    
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Prenu procesumon voko-formiko
      run: docker pull "docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest"
    - name: Kreu dosierujojn por konservi la rezultojn ...
      run: |
        mkdir $GITHUB_WORKSPACE/tgz
        #mkdir $GITHUB_WORKSPACE/tmp
        chmod 777 $GITHUB_WORKSPACE/t??
        ls -l $GITHUB_WORKSPACE
    - name: Eltiru indekson el XML
      run: docker run --name voko-formiko 
        -v $GITHUB_WORKSPACE/revo:/home/formiko/revo/xml 
        -v $GITHUB_WORKSPACE/tgz:/home/formiko/tgz
        docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest 
        formiko inx-eltiro
    - name: Konverti XML al HTML-artikoloj
      run: docker exec -it voko-formiko formiko art-tuto
    - name: Krei SQLite-datumbazojn - unu kun indeksoj, dua indeksoj kaj artikoloj
      run: docker exec -it voko-formiko formiko sql-tuto
    - name: Paku SQLite-datumbazojn kiel ZIP-arĥivo
      run:  docker exec -it voko-formiko formiko sql-zip
    - name: Montru la rezultantajn ZIP-dosierujojn
      run: ls -l $GITHUB_WORKSPACE/tgz

# FARENDA: ŝovu la rezultantajn ZIP-dosierujojn ien: ekz. alpendigu al la ekzistanta versio v2020-mm-dd
