name: make-revo

on:
  push:
    branches:
      - master

## tio funkcias nur por mane kreitaj eldonoj!
##  release:
##    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
##    types: [created, prereleased]

##    # Provizu eldonojn `vLundo` ktp. per SQLite-DB
##    # (alternative oni povus akcepti ĉiun eldonon kaj alpendigi al tiu)
##
##    tags:
##      - vLundo      
##      - vMardo      
##      - vMerkredo      
##      - vĴaŭdo      
##      - vVendredo      
##      - vSabato      
##      - vDimanĉo      


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Elŝutu la dosierojn 
      uses: actions/checkout@v1
      with:
          path: revo-fonto
    - name: Saluto al docker.pkg.github.com
        # https://github.community/t5/GitHub-Actions/Use-docker-images-from-GitHub-Package-Registry/td-p/30407    
        # https://github.com/actions/starter-workflows/blob/master/ci/docker-push.yml    
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Prenu procesumon voko-formiko
      run: docker pull "docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest"
    - name: Kreu dosierujojn por konservi la rezultojn ...
      run: |
        mkdir $GITHUB_WORKSPACE/tgz
        mkdir $GITHUB_WORKSPACE/tmp
        mkdir $GITHUB_WORKSPACE/revo
        chmod 777 $GITHUB_WORKSPACE/t??
        chmod 777 $GITHUB_WORKSPACE/revo
        ls -l $GITHUB_WORKSPACE
    - name: Preparu la vortaron
      run: docker run 
        -v $GITHUB_WORKSPACE/revo:/home/formiko/revo 
        -v $GITHUB_WORKSPACE/tmp:/home/formiko/tmp
        docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest 
        formiko med-medio
    - name: Kreu la tutan vortaron
      run: docker run 
        -v $GITHUB_WORKSPACE/revo-fonto:/home/formiko/revo-fonto 
        -v $GITHUB_WORKSPACE/revo:/home/formiko/revo 
        -v $GITHUB_WORKSPACE/revo-fonto/revo:/home/formiko/revo/xml 
        -v $GITHUB_WORKSPACE/tmp:/home/formiko/tmp
        -v $GITHUB_WORKSPACE/tgz:/home/formiko/tgz
        docker.pkg.github.com/revuloj/voko-formiko/voko-formiko:latest 
        formiko vrt-tuto

# vd. https://github.com/actions/upload-release-asset
    - name: Rigardu la rezulton
      run: |
        #tar -czf revo.tgz $GITHUB_WORKSPACE/revo
        ls -l $GITHUB_WORKSPACE/tmp/*


