name: make-daily-release

on:
  #schedule:
  # ĉiutage matene
  # * is a special character in YAML so you have to quote this string
  #- cron:  '15 8 * * *'
  #- cron:  '34 19 * * 2'
  push:
    branches:
    - master

# https://github.com/actions/create-release
# https://help.github.com/en/actions/reference/development-tools-for-github-actions
# https://github.com/actions/github-script

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Hodiaŭ..."
      run: |
        Tagoj=(Dimanĉo Lundo Mardo Merkredo Ĵaudo Vendredo Sabato)
        echo "::set-env name=TAGO::${Tagoj[ $(date +'%w') ]}"
    - name: "Eĥo..."
      run: |
        echo $TAGO
    - uses: actions/github-script@0.3.0
      name: Movu etikedon al la nuna kap-pozicio
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
          const ref = await github.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,            
              ref: 'heads/master'})
          const sha = ref.data.object.sha
          console.log('HEAD is: '+sha)
          const result = await github.git.createRef({  
             owner: context.repo.owner,
             repo: context.repo.repo,            
             sha: sha,
             ref: 'refs/tags/v${{ env.TAGO }}',
             force: true })
          console.log("RESULT...")
          console.log(result)


       
